### ISSUE TITLE
The each() function is deprecated

### ISSUE THREAD

**Issue by aalcaidep** [maniakalen/yii2workflow#1]
PHP 7.2
yii\base\ErrorException: The each() function is deprecated. This message will be suppressed on further calls in /data/vendor/maniakalen/workflow/src/maniakalen/workflow/components/WorkflowManager.php:144

**Comment by maniakalen** [comment]
New version is released now with the call to each removed.

**Comment by aalcaidep** [comment]
Not working as expected for this example:

`$post['action'] = Array
        (
            [4] => 1
            [5] => 
        )`

**Comment by maniakalen** [comment]
New release was published. Action array should have the format of [ actionId => actionName]
